[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/downloads/
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=49582
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
WebUI\Address=*
WebUI\ServerDomains=*
WebUI\Username=webservices-proxy
WebUI\Password_PBKDF2="@ByteArray(a1uo4KkKy+WfbDjnu0cCTg==:/ziHNcmC/42IbqpcPVF/I4EiOdzb5ODctfGSSKd/STDM2gJqFIH+562Ny0oqwtszXEhpZb3XdhNYKIbGnuLU/g==)"
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=127.0.0.1
WebUI\BypassLocalAuth=true
